[package]
name = "pcomp"
version = "0.2.0"
authors = ["benki"]
edition = "2018"

[dependencies]
image = "0.23"
rayon = "1.3"
mozjpeg = "0.8"
lazy_static = "1.4"
anyhow = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }