[general]
jpeg_quality = 70.0 # 0.0 ~ 100.0%
read_sub_dir = true

[resize]
enable = true
long_side_length = 1600

[sharpness]
enable = true
sigma = 2.0
threshold = 10

[brightness]
enable = true
setting = 10    # -128 ~ 127

[contrast]
enable = false
setting = 0.0   # -100.0 ~ 100.0%
